### ISSUE TITLE
Camera disconnection is not detected and there's no recovery after reconnecting camera

### ISSUE THREAD

**Issue by hekkup** [UFOID/UFO-Detector#15]
Currently need to restart the app if camera is disconnected. CPU load goes to 100% when disconnecting. That seems to be due to image grab and/or copying thread continuing. Also there's no recovery after camera is replugged.

**Comment by hekkup** [comment]
This is partly due to OpenCV. VideoCapture::read() didn't fail properly on camera unplug but it has been fixed in the more recent code: https://github.com/Itseez/opencv/pull/6313
Now only need to add proper checks into UFO Detector. Linux version is currently using OpenCV 2 so can't fix this without moving to OpenCV 3.2 (correct version??).

**Comment by UFOID** [comment]
I am using OpenCV 3.1 on Linux and Window which has the issue you described but other than that works. However, the newest version according to http://opencv.org/downloads.html is 2.4.13. Don't know if it already includes the fix you mentioned
