### ISSUE TITLE
Detector thread is started twice, jamming the system

### ISSUE THREAD

**Issue by hekkup** [UFOID/UFO-Detector#20]
Detector thread is started two times which causes problems. Starting the thread the 2nd time will take some time after program start. I added debug message to the places where it is started and got this in output (these lines are together, nothing cut away from between lines):

```
ActualDetector::start(): Starting detection thread
started normal thread
ActualDetector::checkIfNight(): Starting detection thread
started normal thread
```

As a result, the app will jam eventually taking 100% CPU time and UI becoming unresponsive.

**Comment by UFOID** [comment]
This is strange. Is this a new problem? I am sure I would have noticed that before

**Comment by UFOID** [comment]
In `ActualDetector::start()` the program first starts the thread that checks if it is night. This thread will automatically start the actual detection thread `pThread` if it is night. In `ActualDetector::start()` we sleep for 1 second after starting the `threadNightChecker` and then check if `pThread` runs and only if it doesn't run already we start it. At least thats the idea

**Comment by hekkup** [comment]
Maybe pThread crashes at some point because new thread is started when pThread is null?

**Comment by UFOID** [comment]
I can not reproduce this when testing #19 The thread only starts once

**Comment by hekkup** [comment]
Ok I got it how the night check and detection threads work together. So it's not that. I see you have disabled bird detection in ActualDetector (commit b0ed45d58c0286d24544652c8086bba1fd53552a). Hope that helps, but then we don't have bird detection. At this point we really could help a proper unit test for ActualDetector, especially for the thread functions.

Another idea would be to try to integrate night checking / total light measurement into the normal detection function so that the detection thread wouldn't need to be switched on and off.

**Comment by UFOID** [comment]
I didn't deactivate the bird detection completely. I only deactivated it if the cascade file isn't found/loaded correctly. 

I agree that some unit testing for ActualDetector or the whole detection process would be good. Even better with some defined test video input that can be analyzed over different versions of the detection algorithm. I am focusing on the Raspberry Pi version right now but this is definitely something on my list.

I don't like the idea of intergrating the nightChecking thread with the main detection thread. I don't want to make the main thread more complex and the way the two threads work right now it should (or used to..) work fine

**Comment by UFOID** [comment]
Does this always happen to you or only sometimes? I am really confused about this issue

**Comment by UFOID** [comment]
I'd like to release 0.6.3. Is this still an issue?

**Comment by hekkup** [comment]
I haven't seen jamming problem anymore but I don't know if it really has gone away. Recent thread problem fixes might have fixed it. Oh the wonderful world of thread debugging. :)

**Comment by UFOID** [comment]
Ok. I'll close this for now
