### ISSUE TITLE
Occasionally application crashes during video recording

### ISSUE THREAD

**Issue by hekkup** [UFOID/UFO-Detector#21]
Video recorder thread is started but the app crashes occasionally after that.
This applies at least to commit 15c8942112525243cdd8d10e822641129661b670.
Debug output:

```
"/home/***/Documents/UFO ID/Videos/Capture--2016-05-15--21-32-25temp.avi"
++++++++recorder thread called+++
*** Error in `/home/***/src/UFO-Detector/build-Detector-Desktop_Qt_5_6_0_GCC_64bit-Debug/ufodetector': free(): invalid pointer: 0x00007f0140000078 ***
The program has unexpectedly finished.
```

The video shown on the 1st line is the previous video and it's saved normally.
The recorder thread starts ok, and the next video is being saved in the video folder and can be found from there. The video has "temp" ending so the recorder doesn't finish the job.
Web camera video was being showed during this.
I don't know how this can be reproduced as it seems to happen occasionally.

**Comment by UFOID** [comment]
How big/long is the temp video file?
Does it only happen when using the FFV1 codec?
Do you know if the program made the call to stop the video recording process (crash happens when stopping)?

**Comment by UFOID** [comment]
Please confirm if this happens during video recording or at the end of it i.e. when Recorder::finishedProcess() is called. For me it seems to be the at the end

**Comment by UFOID** [comment]
Although not very often I still occasionally experience crashes when starting the video recording and I have no idea why.
