### ISSUE TITLE
Video list may contain invalid videos

### ISSUE THREAD

**Issue by hekkup** [UFOID/UFO-Detector#23]
Sometimes there's video in the video list but nothing in the video folder, not even a temp video. This can be seen when clicking Play button in which case no video is found. Sometimes the thumbnail image is missing, too. I guess this might happen after application crash or if video recorder fails. Related to #21 and #22.

**Comment by UFOID** [comment]
Are you sure you didn't delete the video from outside the application (or maybe inside the application and the result data file didn't update correctly).
I don't see any scenario where an application crash would cause the video to appear in the list without a video file (not even temp file)

**Comment by hekkup** [comment]
I didn't delete any videos outside the application. I think it has to do with the crashes & other problems like error with result data file writing (#22), and more accurately, UFO Detector data writing is not ACID safe like the database transactions are, so crash at some point of data saving will leave the data in an inconsistent state.

**Comment by UFOID** [comment]
I just encoutered the same problem for the first time. Video in list but not on disk. I am pretty sure it is something new. I never had this before.
Will investigate

**Comment by UFOID** [comment]
`Recorder::finishedRecording(QString picDir, QString filename)` isn't called anymore after finishing encoding. Not sure why

**Comment by UFOID** [comment]
Ok the source of my problem was that I didn't have ffmpeg at the right location. This lead to the Recorder::finishedProcess() never being called (probably shouldn't allow the detection process if encoder wasn't found). After fixing this I cannot reproduce it anymore.
I do get the occasional crash when calling Recorder::finishedProcess() as mentioned in #21 ....

**Comment by UFOID** [comment]
Is this still an issue and if it is can you confirm that you didn't make the same mistake I did with not having the encoder at the right location?

**Comment by hekkup** [comment]
The encoder is at the right location so that's not the problem.
I created a unit test for the method which writes video entries into the result data file. At the basic version of the test (commit 9b2597c7091c5a194c5e33847dd12afb084e47d8) there are no visible problems. The situation is different when that and other related methods are used from the threads -- don't know what will happen then.

**Comment by hekkup** [comment]
I haven't seen this bug for a long time so maybe this could be closed?
