### ISSUE TITLE
Feature to recover temp videos

### ISSUE THREAD

**Issue by hekkup** [UFOID/UFO-Detector#24]
Sometimes when the app crashes or has other problems it leaves temp videos in the video folder. I suggest there should be a feature to recover the temp videos fixing the video name, checking the result data file, and generating a thumbnail image if it was missing. Related to #21, #22, #23.

**Comment by UFOID** [comment]
The temp file may or may not have been closed properly with `theVideoWriter.release();` I don't want to recover a file that could be corrupt/broken. The priority should be to not have it crash when writing the video file.
