### ISSUE TITLE
Lot of flicker in video view when showing video during detection

### ISSUE THREAD

**Issue by hekkup** [UFOID/UFO-Detector#25]
When web camera video is shown in the video view during detection, it has a lot of flicker.

**Comment by UFOID** [comment]
Does flicker mean lag as in low frame rate?
I cannot reproduce this with my webcam devices

**Comment by hekkup** [comment]
There's no lag, it's just flickering, meaning there's a lot of random fast flashing between black color and actual video image.

**Comment by UFOID** [comment]
Can you confirm this only occurs during the detection process? When running it when detection is not running the video is displayed correctly?
Maybe it has to do with the hard coded `displaySize`. Have you tried the fix 6833cf1

**Comment by hekkup** [comment]
Yes, it only happens during detection process and with the latest commit (53781087b112131555f2ae1095b06b25f5cca092). In fact there's some flickering when detection is not running, but it's really very little and not nearly as bad as this.

**Comment by UFOID** [comment]
Sounds like the webcam can't read frames fast enough and returns black image instead? Is this a new issue?

**Comment by hekkup** [comment]
I don't know if it's a new issue because I just now tried this feature. Since I can see the problem, I could probably have a look at it at some point. If anyone else has interest, feel free of course.

**Comment by hekkup** [comment]
Ha, of course. :) Thread yield fixed it.
