### ISSUE TITLE
Feature to test video recording with selected codec

### ISSUE THREAD

**Issue by UFOID** [UFOID/UFO-Detector#26]
It would help when supporting user that experience problems when recording a video if there was an option in the settings to test the video recording.
Something that writes a 10 second (to check framerate / lag) video with the selected codec in the selected folder.

**Comment by hekkup** [comment]
Stuff for a unit test! :)

**Comment by UFOID** [comment]
That of course but there should also be a way for a non developer user to quickly test if his webcam can write a video with the selected codec to the selected folder
