### ISSUE TITLE
Feature to record videos few seconds before positive detection

### ISSUE THREAD

**Issue by hekkup** [UFOID/UFO-Detector#27]
At the moment video recording starts at the same time than the positive detection. It would be really nice if the recorded videos started a few seconds before the actual detection. That would be good for the user and the detection algorithms development. This feature would imply using frame buffer.

**Comment by UFOID** [comment]
I have thought about this before. Obviously a useful feature. It should be possible with a buffer that keeps a few seconds of video input in memory. It would require a lot of rewriting of the Recorder class and the ActualDetector.
I don't see it as a priority at the current stage but definitely a 'nice-to-have' feature in the future.
