### ISSUE TITLE
CLI/Headless Mode Feature

### ISSUE THREAD

**Issue by hekkup** [UFOID/UFO-Detector#29]
For independent observation stations, board PC's like Raspberry Pi, background running etc. it would be nice if the app had a command-line interface / headless mode. That should be relatively easy to do. This shouldn't be a fork from UFO-Detector, but would be best done by just adding a new Qt project next to the current one. The engine would be the same, just the UI layer would be different. This feature is probably not on high priority but would belong to nice-to-have category. Raspberry Pi is probably an exception.

**Comment by hekkup** [comment]
Should we separate the detection engine and different UI's into different repositories? The engine would be the same for each UI.
At least it's possible to start moving the detection engine stuff into a subfolder.
There are some docs over here: https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/

**Comment by kermitas** [comment]
Sources should generally follow modularization pattern (and other good practices as well).

So there should be libraries, well understandable, single responsibility, well tested and documented. Published as an artifact to some repo (like Maven Central) and thus that truly reusable. Examples are: math library, motion detection library (that can depend on math library) and so on...

Then there can be a "wiring project" (that simply make an useage of some libraries [in some versions]). Usually with REST interface and JSON.

On top of that there can be a plenty of UI projects such as GUI, web UI (www) and/or text UI. 

Of course full interaction from a command line (like curl) should possible without any UI.

"Server" (the REST service) while starting should read configuration file (for example: written in JSON) and internally represent it in simple objects (like structs/pojo/dao/case classes). Also library's  constructor should get its configuration in a same way (like a motion detection's library main class - MotionDetection - can take MotionDetectionConfig as an argument). 

Just my two cents from my practice.

**Comment by hekkup** [comment]
I just moved the detector engine into a separate folder, see the pull request https://github.com/UFOID/UFO-Detector/pull/45. It's possible to further put the engine into a separate GitHub repository but the engine should be cleaned and fully decoupled from the UI side for that. I guess there are many projects in GitHub where the modules reside in several repos, for example https://github.com/rootsdev and https://github.com/musescore.

**Comment by hekkup** [comment]
EDIT: the reason for problem below was noise and motion settings needed to be set for ActualDetector as they were not set by default. Fixed now.

I have started a CLI version now but haven't been able to actually detect anything. If you check commit 537adbee3d (and nearby) in my master branch, can you figure what's the problem? I have verified the detector thread in ActualDetector runs by printing out stuff from the thread loop. Also I have verified the camera works by writing a video from the same thread loop. I also changed the motion threshold from 10 to 5 to check if that's the problem. It's not. Any ideas?
