### ISSUE TITLE
MainWindow Camera View resize can go wrong

### ISSUE THREAD

**Issue by UFOID** [UFOID/UFO-Detector#31]
If you play around with the window size too much you get some interesting results

The aspect ratio should always stay the same

![untitled](https://cloud.githubusercontent.com/assets/18535508/15400348/1c4b7b34-1de3-11e6-844b-bb354fc7e062.png)

**Comment by hekkup** [comment]
I think this probably happened because current frame size was being taken as the base of fitting the frame to the view. That way the rounding errors in scaling kept accumulating. But now the camera size is taken as the base so there's no accumulation of error. I haven't seen this bug myself.

**Comment by UFOID** [comment]
Can confirm that fixes it
