### ISSUE TITLE
Night detection is incorrect when camera has automatic brightness adjustment

### ISSUE THREAD

**Issue by hekkup** [UFOID/UFO-Detector#32]
Some camera models such as old Logitech QuickCam have brightness auto-adjustment which causes night detection to give incorrect result.

**Comment by UFOID** [comment]
Can you please explain the issue further? My camera also adjusts the brightness automatically but that hasn't caused a problem for me. In a dark night the frame from the webcam still shows a black/dark view

**Comment by hekkup** [comment]
If I cover the camera lens completely, the image becomes slowly lighter instead of pitch black, reaching the lightness shown in the screenshot. When starting the detection process, the light measurement says total light 102. From ActualDetector::checkIfNight() I see the threshold is 100 so the app thinks it's not night.
![ufo-detector-camera-auto-brightness-160523](https://cloud.githubusercontent.com/assets/1606010/15478681/7c8434ac-2124-11e6-83c4-3e0b1158eaa6.png)

**Comment by UFOID** [comment]
Ok I can see what you mean now. My view during the night is quite different.
Seeing all the image noise I wonder if the detection during the night would still work with that camera.

**Comment by UFOID** [comment]
I close this since it seems to be a specific camera model issue and I don't really know how to deal with the issue.

**Comment by hekkup** [comment]
This issue can be dealt with by using exposure and gain values from the camera. If the values are high, it can be concluded it's night. It's possible to get the values at least in Linux with v4l2 stuff.

**Comment by UFOID** [comment]
That would be a good solution but can we assume the value will always be correct for any webcam device? I have my doubts with that. Also, I am not sure how straight forward a Windows implementation would be
