### ISSUE TITLE
On detection start, the camera image sometimes shows only black

### ISSUE THREAD

**Issue by hekkup** [UFOID/UFO-Detector#35]
When detection is started and video is not shown during detection, the camera image may sometimes show only black. The fact it only happens sometimes would imply some thread problems.

**Comment by UFOID** [comment]
Does checking the checkbox to display the video during detection fix this or will it stay black?

**Comment by hekkup** [comment]
Yes, this only applies to the still image. Video shows ok during detection. During the short pause during detection starting there may be a black frame. I am going to push a commit which hopefully fixes the problem -- just added a mutex to protect the frame as it's accessed from different threads. I did some testing and didn't see the black frame any more.

**Comment by UFOID** [comment]
I am not sure I see which frame is accessed from different threads? As far as I can see updatePixmap() is only being used by one thread at the same time. (I haven't encountered the issue you mention myself)

**Comment by hekkup** [comment]
The other thread is the detector or camera updater thread. The other is Qt's main event loop. The signal-slot system runs in that one.
The current camera frame is shared between those threads so it needs synchronization.
