### ISSUE TITLE
Add build/compile instructions. 

### ISSUE THREAD

**Issue by kermitas** [UFOID/UFO-Detector#41]
Guys, please add build/compile instructions to main README.md.

Especially how one can compile and run it under Ubuntu (that can be on [Pine64](https://www.pine64.com/), Raspberry Pi or other ARM based computer).

**Comment by UFOID** [comment]
Sorry. I haven't added any proper build steps to the readme. I should do that.
It's a Qt project so for Ubuntu there is a simple [installer](https://www.qt.io/download-open-source/). All you need besides that is [OpenCV](http://docs.opencv.org/2.4/doc/tutorials/introduction/linux_install/linux_install.html) and either FFmpeg or avcon.

**Comment by kermitas** [comment]
Thanks for the info.

As a good start to build documentation - and if you want - you can provide here very shortly how I should start with UFO-Detector compilation under Ubuntu (Qt, OpenCV and FFmpeg I will install by myself).

And one more question: how to use UFO-Detector on headless devices? Can I setup it and run via SSH? (I would like to check how Pine64 works with UFO-Detector but [all of my Pines](https://scalaakka.blogspot.com/2016/08/finally-all-five-pine64-come.html) are headless.)

**Comment by UFOID** [comment]
There isn't a headless mode implemented right now. Once I have some free time available I will publish a first version of [UFO Detector for RaspberryPi](https://github.com/UFOID/UFO-Detecor-Pi) which will eventually have a headless mode (and document the build steps properly. Many to-do's left).

**Comment by kermitas** [comment]
Ok, I understand and keeping my fingers crossed.
And can you help me here, now with some hints how to compile sources? (I will be doing that on Ubuntu, probably on Pine64; to start and setup I will connect it to some screen via HDMI)

**Comment by UFOID** [comment]
If you have Qt (and OpenCV) installed on your Ubuntu simply open the project file Detector.pro in Qt. It should load all the resources and allow for a one click build. Check opencv.pri for the defined INCLUDEPATH&LIBS

**Comment by hekkup** [comment]
Headless mode / command line interface is in issue https://github.com/UFOID/UFO-Detector/issues/29.
