### ISSUE TITLE
ActualDetector doesn't always start recorder after detecting object

### ISSUE THREAD

**Issue by hekkup** [UFOID/UFO-Detector#43]
The unit test of ActualDetector tells that bright objects are not always detected. In the current basic test a 10-pixel wide object moves across the screen in about one second. Detection rate is only around 50%. In this kind of controlled setup the detection rate should be 100%.

**Comment by UFOID** [comment]
Looking at `posCounter` I am getting 26 total positive detections for the detectBrightObjects() test which seems to indicate 100%

**Comment by hekkup** [comment]
Ok, in that case the test is catching another issue: the recorder is not always started even if objects are detected allright. The test is verifying the recorder thread has been started. I didn't actually look inside ActualDetector to see what's going on, just figured that the recorder should be started always.

**Comment by UFOID** [comment]
You do test the recording start in the ActualDetector unit test with `QVERIFY(mockRecorderStartCount > 0);` This test always passes for me as far as I can tell

**Comment by hekkup** [comment]
That was the test which was failing. Strange but now it passes for me, too, so the problem went away. I don't know why. Anyway, I'm going to close this issue.
