### ISSUE TITLE
Add detection of dark objects

### ISSUE THREAD

**Issue by hekkup** [UFOID/UFO-Detector#44]
Currently UFO Detector only detects bright objects. Add detection of dark objects, too, as many UFO's look dark, e.g. the so-called black triangles. This means more requirements for the detection algorithm as normally dark-looking objects like birds must then be distinguished.

**Comment by UFOID** [comment]
You are correct that ideally the algorithm should also consider dark objects. When I started developing it I was testing different approaches but anything that included dark and bright object was resulting in way to many false-positives. The issue aren't just birds (those could be filtered out with object detection) but mainly insects and also just dust/leaves flying around in the air.
Insects and dust will only appear as a small dot of dark pixels which seems impossible to distinguish from a dot of pixels coming from a "real" UFO. The only thing that gave it away when watching a captured video of an insect flying through the camera view is its uneven and changing flying pattern. However, I wasn't confident enough with using this little information to develop an algorithm that can distinguish an insect flying pattern from a UFO flying pattern (for which we don't have a defined pattern for).
