### ISSUE TITLE
Change detection area file format to polygon-based

### ISSUE THREAD

**Issue by hekkup** [UFOID/UFO-Detector#46]
Currently the detection area file is point-based. Is there any important reason for that? I would suggest we changed it to polygon-based. There would be several benefits from it. Polygon-based file format would be faster to save and load. The file could be edited by hand (I'm thinking about CLI based usage). Polygons could be also managed by the detection area edit dialog much easier, e.g. there would be no need to re-define the area each time and it would be possible to edit the polygon in the editor.

**Comment by UFOID** [comment]
I didn't consider a polygon-based approach before but I agree with the advantages you listed.
I am not sure I understand what you mean with "need to re-define the area each time". The only time the user has to re-define the area is when changing the camera resolution (or when changing the camera view/position obviously). I guess the advantages with a polygon-based approach is that it could just scale it automatically according to the resolution.

**Comment by hekkup** [comment]
I mean you can't edit the area once it has been defined. If you want different area, you need to create a new one.
For editing, polygon-based approach would work better for both code and for usage.
