### ISSUE TITLE
Video doesn't get written in Ubuntu 16.04

### ISSUE THREAD

**Issue by hekkup** [UFOID/UFO-Detector#47]
I noticed that the video doesn't get written in Ubuntu 16.04.1 LTS. OpenCV version is 2.4.9.1. Version 3 is not available in the normal repository. Only a header 5686 bytes long gets written.

It might be possible to bypass cv::VideoWriter by writing video with Qt Multimedia framework or GStreamer which is the backend of the multimedia framework and possibly also the backend of OpenCV.

**Comment by hekkup** [comment]
This issue has been fixed in OpenCV 3.1.0: https://github.com/opencv/opencv/issues/5439

There are a few solutions:
- use lossy/packed codec like H264 (but this option is not given to user)
- install OpenCV 3.1.0

**Comment by hekkup** [comment]
7c292fa adds OpenCV 3.1.0 installation instructions.

**Comment by UFOID** [comment]
Sorry for the delay. I was without internet.
Good find. I merged it. Thanks
