### ISSUE TITLE
Use fixed frame rate for detection algorithm

### ISSUE THREAD

**Issue by hekkup** [UFOID/UFO-Detector#57]
Detection algorithm parameter meaning will change when frame rate changes, making detection algorithm perform differently in different conditions. Frame rate changes due to automatic exposure time adjustment by web camera. If frame rate can't be achieved due to e.g. long exposure time on low light conditions, parameter values should be adjusted for changed conditions.

**Comment by UFOID** [comment]
You propose to have the main detection algorithm run at a fixed (frame) rate as oppose to just as fast as it can. If I understand it correctly you see the main benefit of this in the algorithm performing the same in various conditions. Are there any other benefits from this?

**Comment by hekkup** [comment]
Waste of resources comes to mind, too.

An example of disadvantage of maximum speed video: if there's an object in the video and it's moving relatively slowly, how would you detect it at 100 FPS? The motion would be more noticable at 25 FPS, or at least the algorithm would be calibrated to work at a known frame rate.

Varying frame rate changes the meaning of algorithm parameters. For example: an object moving at the same speed would look like 5 pixel movement during day and 15 pixel movement at night due to longer exposure time. Then the motion threshold would be different for each situation even if the target is the same.

**Comment by hekkup** [comment]
I did some tests with my camera when I was fixing video jitter issue (#51). I noticed in good light the frame rate was able to stay normal 25 FPS. In low light the exposure time climbed to 2-4 times the normal time (1-3 duplicate frames in addition to the grabbed frames) so it meant camera frame rate was as low as 6 FPS.

**Comment by hekkup** [comment]
Moreover, if VideoBuffer is used for detection algorithm as well, we could get rid of duplicate frame grabbing threads. One frame producer, many frame consumers. That would mean improvement for resource usage.

**Comment by hekkup** [comment]
Buffering would also enable fixing #27.

**Comment by UFOID** [comment]
I understand. The buffer could be implemented in to the Camera. Meaning there is one thread retrieving a frame from VideoCapture 25 times per second. Then, it hands them out one-by-one to the different threads that need a frame.
The recorder would start with the frame at beginning of the buffer and not the most recent one. 

I am not sure about how to deal with the issue regarding the long exposure at night which is specific to the camera. Do we accept duplicate frames or do you propose anything else?

**Comment by hekkup** [comment]
Duplicate frames are ok. At the moment, info about frame duplication is stored only in BufferedVideoFrame.m_duplicateCount (recorder.h), without actually duplicating the frame. If the detection algorithm can be modified to handle that, then this way can continue to be used.

A simpler way would be to store duplicate frames separately, just maybe have a flag that this frame is a duplicate of the previous frame (useful info in motion detection and frame writing).
