### ISSUE TITLE
Can't run testRecorder

### ISSUE THREAD

**Issue by UFOID** [UFOID/UFO-Detector#64]
The issue is with the mockVideoBuffer class. In both my windows and ubuntu environment. I keep on getting a similar error. 

I run the test using `make check`

> 
> videobuffer.o: In function `VideoBuffer::capacity()':
> videobuffer.cpp:(.text+0x0): multiple definition of `VideoBuffer::capacity()'
> mockvideobuffer.o:mockvideobuffer.cpp:(.text+0x50): first defined here
> videobuffer.o: In function `VideoBuffer::count()':
> videobuffer.cpp:(.text+0x10): multiple definition of `VideoBuffer::count()'
> mockvideobuffer.o:mockvideobuffer.cpp:(.text+0x40): first defined here
> videobuffer.o: In function `VideoBuffer::stopWait()':
> videobuffer.cpp:(.text+0x20): multiple definition of `VideoBuffer::stopWait()'
> mockvideobuffer.o:mockvideobuffer.cpp:(.text+0x60): first defined here
> videobuffer.o: In function `VideoBuffer::VideoBuffer(int, QObject*)':
> videobuffer.cpp:(.text+0x30): multiple definition of `VideoBuffer::VideoBuffer(int, QObject*)'
> mockvideobuffer.o:mockvideobuffer.cpp:(.text+0x0): first defined here
> videobuffer.o: In function `VideoBuffer::VideoBuffer(int, QObject*)':
> videobuffer.cpp:(.text+0x30): multiple definition of `VideoBuffer::VideoBuffer(int, QObject*)'
> mockvideobuffer.o:mockvideobuffer.cpp:(.text+0x0): first defined here
> videobuffer.o: In function `VideoBuffer::pushFrame(BufferedVideoFrame*)':
> videobuffer.cpp:(.text+0x110): multiple definition of `VideoBuffer::pushFrame(BufferedVideoFrame*)'
> mockvideobuffer.o:mockvideobuffer.cpp:(.text+0x70): first defined here
> videobuffer.o: In function `VideoBuffer::waitNextFrame()':
> videobuffer.cpp:(.text+0x1a0): multiple definition of `VideoBuffer::waitNextFrame()'
> mockvideobuffer.o:mockvideobuffer.cpp:(.text+0xa0): first defined here
>

**Comment by hekkup** [comment]
The reason is VideoBuffer class is defined twice, first in mockvideobuffer.cpp, then in videobuffer.cpp. The solution is to remove the videobuffer.cpp from the project file. It's better to use mock objects than real ones.

**Comment by UFOID** [comment]
Fixed in #65
