### ISSUE TITLE
Add testreport to testsuite runner

### ISSUE THREAD

**Issue by UFOID** [UFOID/UFO-Detector#66]
Previously I ran my tests with `./testVideoBuffer/testvideobuffer -xml -o testvideobufferResult.xml ` etc
I would like to use the improved testsuite and simply call `make check` and also get the reports in xml.
How do I implement that in to testsuite?

**Comment by hekkup** [comment]
Wrap around shell script? Would it be enough if a script just printed start and end XML tags, e.g.
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuite` name="ufo-detector-engine" performDateTime="01-01-2017 12:20:20" commit="123456">
...
(output from tests here)
...
</testsuite>
```
The output from a test case looks good to append one after another, only the XML identification line should be removed.

**Comment by UFOID** [comment]
I would like to implement it in the runner

```
unix:!macx {
    LIB_PATH=$${TOP_BUILD_DIR}/lib:\$\$LD_LIBRARY_PATH
    test.commands=for d in $${SUBDIRS}; do origdir="\$$PWD" && cd "\$$d" && LD_LIBRARY_PATH=$$LIB_PATH && $(MAKE) test && cd "\$$origdir" || exit 1; done
}
```

so each test produces its respective xml file. I don't want to modify the xml since it will be processed by the xUnit Jenkins plugin.

I tried modifying the command above but wasn't successful.
