### ISSUE TITLE
Corrupted result data file is not dealt with

### ISSUE THREAD

**Issue by hekkup** [UFOID/UFO-Detector#67]
I ended up with a corrupted result data file for some reason. DataManager needs to be tested better for that. The result data file was missing few characters at the end of the last `<video>` entry, as well as the last `</UFOID>` tag.

The problem is the application doesn't care about the corruption but just continues. I didn't test what happens if more entries are added to the file when it's corrupt, but I'd guess it's not too nice to watch.

The desired action would be that the app would show an error message, asking whether or not to fix the file. If the user chooses to fix the file automatically, the app should try rescuing as many entries in the file as possible and as many videos & thumbnail images as possible, and give a report about what was done.

Lightweight approach would be to just give an error message explaining the situation and quit.

**Comment by UFOID** [comment]
[QDomDocument::setContent](https://doc.qt.io/qt-5/qdomdocument.html#setContent) can show exactly where any errors are. Through this we could either ignore or remove the lines containing errors.
