### ISSUE TITLE
Segmentation fault on wrong camera size (Raspberry)

### ISSUE THREAD

**Issue by hekkup** [UFOID/UFO-Detector#69]
If camera size is set wrong in the settings, it causes segmentation fault in Raspberry Pi. Tested with OpenCV 3.2.0 which might have to do something with it. Setting correct camera dimensions in config file will run normally. Segfault doesn't happen in PC side (Linux) even if camera dimensions are incorrect (OpenCV 3.1.0).

**Comment by bollerdominik** [comment]
I have noticed that awell. I have noticed that as well. The current ways to handle wrong specified resolution or other camera issues  don't seem to catch the error on Raspberry

**Comment by UFOID** [comment]
I have noticed that as well. The current ways to handle wrong specified resolution or other camera issues don't seem to catch the error on Raspberry
