### ISSUE TITLE
Windows 10 - ucrtbase.dll

### ISSUE THREAD

**Issue by kff322** [UFOID/UFO-Detector#70]
Faulting application name: Detector.exe, version: 0.0.0.0, time stamp: 0x5905f510
Faulting module name: ucrtbase.dll, version: 10.0.15063.413, time stamp: 0x5ba8b66e
Exception code: 0xc0000409
Fault offset: 0x00000000000734be
Faulting process id: 0x3024
Faulting application start time: 0x01d31213919ffb15
Faulting application path: C:\Program Files (x86)\Detector 0.7.7\Detector.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 328feb0c-eb99-4332-9282-027f160a277a
Faulting package full name: 
Faulting package-relative application ID: 

UFO detector crashes frequently leaving this error message, its usually the same one involving 'ucrtbase.dll'

Also I would like to thank you for this fantastic Project! I wish more than 2 people were working on it.

My Computer Specs - Windows 10 x64 - AMD FX-8350, ATI R9 200 Series Graphics Card, 32 GB of RAM and an NVEM SSD for my system drive that detector.exe runs on. The only operating system Detector is stable, on my computer at least is on Windows 7. Also if the program is run in compatibility for Windows 8, it works a lot better for some strange reason.

Thanks

**Comment by hellbet** [comment]
Same issues here, ucrtbase.dll crashes on each and every positive detection.

**Comment by UFOID** [comment]
Hi what video resolution are you guys running the detection at?

**Comment by hellbet** [comment]
As far as I am concerned, I solved the issue by changing resolution from a guessed 800x600 to the real definition of my A/D USB stick, that is 720x576, Pal. I haven't understood previously the 700 lines camera (which is around 1024x768 pixels BTW) resolution was downgraded by the cheap converter. No more capturing issue since. I'd recommend to double check the input resolution especially if you use an A/D USB converter with STK1160 cheap processing unit.

**Comment by linuxsuperuser** [comment]
I am running 2 resolutions over 3 cameras
1600x1200 – Works Perfectly ($35 EKEN 9 Series Gopro Knockoffs)
1280x720 – Skips and looks Jittery (Logitech HD Camera 990)

So the high resolutions work fine – even on my slower computer, so It would have to some kind of driver or camera limitation that applies to Logitech camera / driver combinations only. Well I’ll replace it.

Thanks for the support!
Keith

Sent from Mail for Windows 10

**Comment by MoSkyWatch** [comment]
I'm running a win 10, 2.20ghz, 64-bit (Inspiron 3558). 
Having issues with getting the program to work.
When I select detection area it says, 
Could not find area file: 
Check area file path in settings.
Also where it says, Select webcam, it just says, webcam 1.
When I try to start detection it says, Failed to open the detection area file. Please create it in Settings dialog or manually.

I'm not a computer expert so I have no idea about what to do.
Also I'm using a Logitech c920 webcam. 
Has anyone else had these issues?
Does this ufoid program work with Windows 10?

**Comment by kff322** [comment]
Ive had this same issue - This is how I fixed it:
1. Copy any .xml file to your desktop
2. Open it in notepad
3. Select all > hit delete so there is nothing > Save
4. Now move the file into the UFO detector directory
5. Go into settings and select your empty xml file.
6. Restart and then you should be good.

Good Luck
Keith

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by MoSkyWatch** [comment]
Ok I did what you said to do and when I select detection area there is just a white screen. It's not showing anything from my webcam. It is activating my webcam but just shows a white screen. Thanks for your help.

**Comment by MoSkyWatch** [comment]
Wait a minute, I just selected take picture and it actually worked. Now I'm begining to have hope.:)

**Comment by MoSkyWatch** [comment]
Ok, I got as far as connecting the dots for the detection area, but when I go to save to file an Error message comes up??? Any thoughts???

**Comment by UFOID** [comment]
@MoSkyWatch  Please keep issues related to the issue topic (ucrtbase.dll). I have emailed you for further clarification
@kff322 Thanks for providing support. The source file on the master branch include the fix to automatically create the xml file if not found. I have yet to compile and upload the binaries for this version

**Comment by MoSkyWatch** [comment]
Sorry I'm new to all of this forum stuff.

**Comment by MoSkyWatch** [comment]
Just wondering if there is any new updates to the ufoid software.
Thanks

Josh Hulsey
Missouri SkyWatcher

**Comment by ceauce** [comment]
Hi UFOID,

This software deserves more recognition !!

Is there a way I can feed my POE IP camera into UFOID? 

How much would it cost to update UFOID to include POE IP cameras?

 Is there a way I could help promote UFOID ? 

Paul
MADAR / NICAP MADAR III INTERNATIONAL NETWORK
MADAR passive Radar 131
MADAR Node 131

**Comment by linuxsuperuser** [comment]
A New Project seems to be eclipsing this one in terms of its ability to
film UFOs
In addition to the hardware and sensors being used is a major step up from
what the UFOID program can do
https://skyhub.org/

KF
