### ISSUE TITLE
Should ask confirmation when deleting a video

### ISSUE THREAD

**Issue by hekkup** [UFOID/UFO-Detector#8]

**Comment by UFOID** [comment]
I am not sure about this. I like being able to delete many videos quickly without having to confirm each deletion but I can understand that accidently permanently deleting a video would be bad.

My use case is following:
Leave detection process running for a long time. Come back to see there were let’s say 20 video recorded during the timeframe. I click play on the first video and watch the video. To play the next video I click the “go to next file” button in my video player which plays the next video in the folder.  I repeat this until I am at the last video in the folder. If none of the videos show anything interesting I just keep on clicking “Delete” in the Detector and easily delete a few dozen videos in a few seconds

**Comment by hekkup** [comment]
Ok. There are several possibilities to achieve deletion which is easy and safe at the same time:
- We can add selection of multiple videos either by Ctrl+clicking them and/or by having a little checkbox or +/- symbol in a video widget for selection. Then we'd have a button or context menu item "Delete selected".
- Have a setting to disable/enable delete confirmation.
- Move the videos to Trash.

I'd prefer the 1st way as it's a standard way. The multiple selection would keep the door open also for having the app do more things for the selected videos, such as marking multiple videos at the same time for upload.

**Comment by UFOID** [comment]
I agree completely 
option 2: I don't want to add to many options to the settings dialog
option 3: Very platform/OS specific

Option 1 with a checkbox and a "Delete selected" button sounds the best
