### ISSUE TITLE
Webcam view refresh rate is very low (Linux)

### ISSUE THREAD

**Issue by hekkup** [UFOID/UFO-Detector#9]
Refresh rate can be even something like 0.1 FPS or so. That's low compared to VLC which shows webcam video at ~24 FPS or more.

**Comment by UFOID** [comment]
I have also encountered this in my previous attempts of compiling it in Linux. If I remember correctly my tests showed that if I just have one thread that both reads from the webcam and updates the GUI the frame rate is within the normal rate. However, if I use the current multi-thread approach it slows down significantly. This seems to be a Linux specific problem. Not sure why. I don’t have this issue on Windows

**Comment by UFOID** [comment]
Reopened? Does that mean the yielding didn't solve the issue?:(

**Comment by hekkup** [comment]
No no, I just thought it's not fixed in the main repository, just in my fork. Let's close it as soon as the fix is in the main repo. :)

**Comment by UFOID** [comment]
Oh ok. Fair enough. I am glad then:)
Will check in a bit
